### ISSUE TITLE
elasticsearch/elasticsearch dependency no longer available

### ISSUE THREAD

**Issue by frnadame** [ruflin/Elastica#2233]
As this module uses "elasticsearch/elasticsearch" [as a dependency](https://github.com/ruflin/Elastica/blob/8.x/composer.json#L21) and this module is no longer available in the [github repo ](https://github.com/elastic/elasticsearch-php)
![image](https://github.com/user-attachments/assets/997df814-e324-4049-9fbc-f67d38477ca7)

Is there any plan to change this dependency to another? or is there any plan to point to a 'legacy' version stored somewhere else?

**Comment by davidesigner** [comment]
Same problem for me, our deployments are blocked.

**Comment by y4roc** [comment]
Same problem for me. All pipelines failed in my projects.

**Comment by davidesigner** [comment]
Answer here: https://discuss.elastic.co/t/some-of-our-public-repositories-are-not-available-atm/369726

This should be resolved soon

**Comment by ruflin** [comment]
Looks like this issue will resolve itself hopefully very quickly as soon as the repos are public again. @davidesigner Thx for the link to the discuss topic.

**Comment by frnadame** [comment]
> Answer here: https://discuss.elastic.co/t/some-of-our-public-repositories-are-not-available-atm/369726
> 
> This should be resolved soon

Glad to see that this is a temporary issue and will be fixed soon.
Thanks for the info @davidesigner.

**Comment by ruflin** [comment]
Seems the repository is publicly available again. Going to close this issue. Please reopen in case the issue still exists.
